import Header from '@/components/Header'
import MainContainer from '@/components/MainContainer'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import { Toaster } from 'sonner'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Header />
        <MainContainer>
          {children}
        </MainContainer>
        <Toaster position='top-center' richColors />
      </body>
    </html>
  )
}
