import { CarouselImage, MenuItemCategory, Opinion } from '@/app/types/types'

export const CAROUSEL_MAIN_IMAGES: CarouselImage[] = [
	{ src: '/img/carousel-1.jpg' },
	{ src: '/img/carousel-2.jpg' },
]

export const OPINIONS: Opinion[] = [
	{
		author: 'Edward T',
		date: '01.07.2024',
		message: 'Restauracja Spoko w Sopocie to prawdziwa perełka nadmorskiej gastronomii. Położona w urokliwym miejscu, tuż przy plaży, oferuje nie tylko przepiękne widoki na morze, ale również doskonałą kuchnię. Menu jest różnorodne i zadowoli zarówno miłośników tradycyjnych polskich smaków, jak i tych poszukujących bardziej egzotycznych dań. Świeże składniki, profesjonalna obsługa i przyjazna atmosfera sprawiają, że każda wizyta w Spoko to wyjątkowe doświadczenie. To idealne miejsce na romantyczną kolację, spotkanie z przyjaciółmi czy rodzinny obiad. Gorąco polecam!',
		rate: 5,
	},
	{
		author: 'Julia B',
		date: '3 miesiący temu',
		message: 'Dawno nie spotkaliśmy tak przemiłej i kontaktowej obsługi-to pierwszy aspekt, dla którego chce się wracać w takie miejsca! Po drugie-lokalizacja, myślę że siedząc latem na patio z widokiem na morze można się zakochać! Przechodząc do sedna-jedzenie. Uważam że sposób podania, kompozycje i jakość składników, którą jest wyczuwalna w każdym kęsie sprosta nawet najbardziej wymagającym podniebieniom :) Z pewnością wrócimy w to miejsce!',
		rate: 5,
	},
	{
		author: 'Pokochaj K',
		date: '2 miesiący temu',
		message: 'Spoko miejsce z klimatem i smacznym jedzeniem. Nero Di Seria, Bowle z Kurczkiem, Spaghetti dla dzieci wyśmienite, zupa rybna klasyczna mogłaby być bardziej treściwa. Sangria i lemoniada mega orzeźwiające. Jestem na tak i wpadnę tu jeszcze będąc na kempingu.',
		rate: 4,
	},
	{
		author: 'Kinga B',
		date: '2 miesiący temu',
		message: 'Cudowne miejsce z fantastyczną obsługa i atmosferą. Jedzenie przepyszne - polecam burgery, bardzo smaczna bułka i świeże składniki. Dodatkowo piękny widok na morze. Pani, która nas obsługiwała była uśmiechnięta, naturalna i niesamowicie kontaktowa. Mało jest już takich osób. Serdecznie dziękujemy za cudowne chwile. Ogromny plus na możliwość przyjścia z pupilami! ❤️ Pozdrawiamy serdecznie (buldożki francuskie Frania&Mia)♥️',
		rate: 5,
	},
	{
		author: 'Anna O',
		date: '5 miesięcy temu',
		message: 'Super miejsce, a obiad mega pyszny. Najlepsza lemoniada jaka piłam. Dorsz z purée ziemniaczano bazyliowym i boczniakami po kaszubsku, palce lizać',
		rate: 5,
	},
]
export const menuItemCategories: MenuItemCategory[] = [
	'Dania główne',
	'Pizza',
	'Burgery',
	'Dla dzieci',
	'Dodatki',
	'Desery',
	'Napoje',
	'Śniadania',
	'Przystawki',
	'Zupy',
	'Bowle',
	'Vege',
	'Dania rybne',
	'Owoce morza',
	'Dania mięsne',
	'Klasyczne koktaile',
	'Na ciepło',
	'Herbata',
	'Kawa',
	'Napoje zimne',
	'Piwo butelkowe',
	'Piwo bezalkoholowe',
	'Piwo beczkowe',
	'Piwo smakowe',
	'Wina Białe',
	'Wina Czerwone',
	'Wina Musujące',
	'Drinki',
	'Whisky',
	'Rum',
	'Gin',
	'Tequila',
	'Cognac / Brandy',
	'Wódka',
	'Napoje alkoholowe',
	'Napoje bezalkoholowe',
	'Napoje łekkoprocentowe',
	'Inne'
]


// export const MENU_ITEMS: MenuItemType[] = [
// 	// BREAKFAST
// 	{
// 		name: 'Śniadanie polskie (500 g)',
// 		price: 39,
// 		description: 'Jajecznica z 3 jaj na maśle / wędlina / ser zółty / serek wiejski / pomidor / ogórek / pieczywo / masło',
// 		category: 'Śniadania',
// 		image: '/img/menu/sniadanie-polskie.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'SHAKSHUKA VEGE (500 G)',
// 		price: 39,
// 		description: '3 jajka sadzone / salsa pomidorowa z fasolką i ciecierzycą / cebula / marchewka / pieczywo / masło',
// 		category: 'Śniadania',
// 		image: '/img/menu/shakshuka-wege.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'SHAKSHUKA MIĘSNA (500 G)',
// 		price: 39,
// 		description: '3 jajka sadzone / salsa pomidorowa z fasolką i ciecierzycą / cebula / marchewka / pieczywo / masło / mięso',
// 		category: 'Śniadania',
// 		image: '/img/menu/shakshuka-miesna.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Śniadanie mięsne (450 g)',
// 		price: 39,
// 		description: '2 jaja sadzone / 2 grillowane frankfurterki / ogórek piklowany / pomidor / sos aioli / pieczywo / masło',
// 		category: 'Śniadania',
// 		image: '/img/menu/sniadanie-miesne.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Chałka z grillowanym kurczakiem (400 g)',
// 		price: 42,
// 		description: 'Grillowany kurczak / 2 jajka w koszulkach / rukola / pomidorki koktajlowe / sos aioli / sałatka ze świeżych warzyw',
// 		category: 'Śniadania',
// 		image: '/img/menu/chalka-z-grillowanym-kurczakiem.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Chałka z krewetkami (350 g)',
// 		price: 42,
// 		description: '4 krewetki tygrysie / 2 jajka w koszulkach / kremowy sos / rukola / sałatka ze świeżych warzyw',
// 		category: 'Śniadania',
// 		image: '/img/menu/chalka-z-krewetkami.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Chałka vege z guacamole (350 g)',
// 		price: 45,
// 		description: '2 jajka w koszulkach / guacamole / pomidorki koktajlowe / rukola / sałatka ze świeżych warzyw',
// 		category: 'Śniadania',
// 		image: '/img/menu/chalka-vege-z-guacamole.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Naleśniki (350 g)',
// 		price: 34,
// 		description: 'Twarożek waniliowy / świeże owoce / sos wiśniowy',
// 		category: 'Śniadania',
// 		image: '/img/menu/nalesniki.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	// STARTERS
// 	{
// 		name: 'Antipasti: Śledź w sosie tzatziki (70 g)',
// 		price: 17,
// 		description: '',
// 		category: 'Przystawki',
// 		image: '/img/menu/sledz-w-sosie-tzatziki.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Antipasti: Guacamole (70 g)',
// 		price: 17,
// 		description: '',
// 		category: 'Przystawki',
// 		image: '/img/menu/guacamole.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Antipasti: Pasta z makreli (70 g)',
// 		price: 17,
// 		description: '',
// 		category: 'Przystawki',
// 		image: '/img/menu/pasta-z-makreli.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Chrupiące dary morza',
// 		price: 42,
// 		description: '5 x krążki kalmara / 5 x panierowane krewetki / sos aioli',
// 		category: 'Przystawki',
// 		image: '/img/menu/crispy-gifts-of-the-sea.jpg',
// 		isOrderable: true,
// 		isRecommended: true,
// 	},
// 	{
// 		name: 'Aromatyczne krewetki (160 g)',
// 		price: 42,
// 		description: '4 x krewetki / rukola / guacamole / pomidorki koktajlowe',
// 		category: 'Przystawki',
// 		image: '/img/menu/aromatic-shrimps.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Bruschetta z wędzonym serem (160 g)',
// 		price: 32,
// 		description: 'Bruschetta z wędzonym serem',
// 		category: 'Przystawki',
// 		image: '/img/menu/bruschetta-z-wedzonym-serem.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Bruschetta z szynką parmeńską (160 g)',
// 		price: 34,
// 		description: '',
// 		category: 'Przystawki',
// 		image: '/img/menu/bruschetta-z-szynka-parmenska.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Bruschetta z krewetkami (160 g)',
// 		price: 36,
// 		description: '',
// 		category: 'Przystawki',
// 		image: '/img/menu/bruschetta-z-krewetkami.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Tatar z łososia (500 g)',
// 		price: 42,
// 		description: 'Ręcznie siekany świeży łosoś / cebula czerwona / świeży ogórek / musztarda francuska / sos sojowy / pieczywo',
// 		category: 'Przystawki',
// 		image: '/img/menu/tatar-z-lososia.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Tatar wołowy (200 g)',
// 		price: 49,
// 		description: 'Ręcznie siekana polędwica wołowa / cebula / ogórek konserwowy / kapary / musztarda francuska / zółtko jaja / pieczywo',
// 		category: 'Przystawki',
// 		image: '/img/menu/tatar-wolowy.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	// SOUPS
// 	{
// 		name: 'Krem z pomidorów (300 ml)',
// 		price: 25,
// 		description: '',
// 		category: 'Zupy',
// 		image: '/img/menu/krem-z-pomidorow.jpg',
// 		isOrderable: true,
// 		isRecommended: true,
// 	},
// 	{
// 		name: 'Zupa rybna (350 ml)',
// 		price: 22,
// 		description: '',
// 		category: 'Zupy',
// 		image: '/img/menu/zupa-rybna.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	// BOWLS
// 	{
// 		name: 'Bowl z grillowanym kurczakiem (450 g)',
// 		price: 42,
// 		description: 'Guacamole / 2 jajka w koszulkach / mix sałat / pomidorki koktajlowe / sos śmietankowy',
// 		category: 'Bowle',
// 		image: '/img/menu/bowl-z-grillowanym-kurczakiem.jpg',
// 		isOrderable: true,
// 		isRecommended: true,
// 	},
// 	{
// 		name: 'Bowl z grillowanymi krewetkami (450 g)',
// 		price: 42,
// 		description: 'Guacamole / 2 jajka w koszulkach / mix sałat / pomidorki koktajlowe / sos śmietankowy',
// 		category: 'Bowle',
// 		image: '/img/menu/bowl-z-grillowanymi-krewetkami.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	//VEGE
// 	{
// 		name: 'Bowl Vegan (450 g)',
// 		price: 49,
// 		description: 'Guacamole / czerwona cebula / pomidorki koktajlowe / jalapeno / rukola / parmezan',
// 		category: 'Vege',
// 		image: '/img/menu/bowl-vegan.jpg',
// 		isOrderable: true,
// 		isRecommended: true,
// 	},
// 	{
// 		name: 'Gnocchi Vege (400 g)',
// 		price: 36,
// 		description: 'Warzywny gulasz a la ratatouille / parmezan / natka pietruszk',
// 		category: 'Vege',
// 		image: '/img/menu/gnocchi-vege.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Frytki Belgijskie (250 g)',
// 		price: 39,
// 		description: 'Guacamole / czerwona cebula / pomidorki koktajlowe / jalapeno / rukola / parmezan',
// 		category: 'Vege',
// 		image: '/img/menu/frytki-belgijskie.jpg',
// 		isOrderable: true,
// 		isRecommended: true,
// 	},
// 	// FISH DISHES
// 	{
// 		name: 'Klasyczny smażony filet z dorsza (450 g)',
// 		price: 56,
// 		description: 'Panierowany filet z dorsza / bułka maślana / krążki cebulowe / świeży ogórek / sałata / sos aioli / frytki / ketchup',
// 		category: 'Dania rybne',
// 		image: '/img/menu/klasyczny-smazony-filet-z-dorsza.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Pieczony filet z łososia (400 g)',
// 		price: 59,
// 		description: 'Risotto kremowo-szafranowe / zielony groszek / parmezan',
// 		category: 'Dania rybne',
// 		image: '/img/menu/pieczony-filet-z-lososia.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Pieczona tuszka pstrąga (500 g)',
// 		price: 56,
// 		description: 'Łódeczki ziemniaczane / warzywny gulasz a la ratatouille',
// 		category: 'Dania rybne',
// 		image: '/img/menu/pieczona-tuszka-pstraga.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Dorsz burger (450 g)',
// 		price: 56,
// 		description: 'Panierowany filet z dorsza / bułka maślana / krążki cebulowe / świeży ogórek / sałata / sos aioli / frytki / ketchup',
// 		category: 'Dania rybne',
// 		image: '/img/menu/dorsz-burger.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	// SEAFOOD
// 	{
// 		name: 'Paella z owocami morza (450 g)',
// 		price: 56,
// 		description: 'Mule / krewetki / raki / pomidorki koktajlowe / risotto z szafranem / pietruszka',
// 		category: 'Owoce morza',
// 		image: '/img/menu/paella-z-owocami-morza.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Mule w sosie maślano-winny (400 g)',
// 		price: 56,
// 		description: 'Winno - maślany sos / bagietka / natka pietruszki',
// 		category: 'Owoce morza',
// 		image: '/img/menu/mule-w-sosie-maslano-winny.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Spaghetti nero di sepia (450 g)',
// 		price: 56,
// 		description: 'Autorski sos maślano - winny / łosoś / krewetki / pomidorki koktajlowe / pietruszka',
// 		category: 'Owoce morza',
// 		image: '/img/menu/spaghetti-nero-di-sepia.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Plater owoców morza (700 g)',
// 		price: 129,
// 		description: 'Krewetki / mule / ośmiorniczki baby / małże vongole / raki / bagietka',
// 		category: 'Owoce morza',
// 		image: '/img/menu/plater-owocow-morza.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Plater rozpusty (700 g)',
// 		price: 129,
// 		description: 'Krewetki Butterfly w chrupiącej panierce / złociste krążki kalmara / fileciki z dorsza w panko / frytki / sos sweet chilli / sos aioli',
// 		category: 'Owoce morza',
// 		image: '/img/menu/plater-rozpusty.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	// MEAT DISHES
// 	{
// 		name: 'Riggatoni z kurczakiem (300 g)',
// 		price: 56,
// 		description: 'Sos BBQ Mississippi / łódeczki ziemniaczane / surówka coleslaw',
// 		category: 'Dania mięsne',
// 		image: '/img/menu/riggatoni-z-kurczakiem.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Wolno pieczone żeberka wieprzowe (700 g)',
// 		price: 69,
// 		description: 'Sos BBQ Mississippi / łódeczki ziemniaczane / surówka coleslaw',
// 		category: 'Dania mięsne',
// 		image: '/img/menu/wolno-pieczone-zeberka-wieprzowe.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Roladka z kurczaka owinięta szynką parmeńską (450 g)',
// 		price: 56,
// 		description: 'Bryndza / suszone pomidory / bazylia / puree ziemniaczano – bazyliowe / marchewka paryska',
// 		category: 'Dania mięsne',
// 		image: '/img/menu/roladka-z-kurczaka.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Poliki wołowe (450 g)',
// 		price: 66,
// 		description: 'Puree ziemniaczano – bazyliowe/ buraczki w marynacie',
// 		category: 'Dania mięsne',
// 		image: '/img/menu/poliki-wolowe.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Polędwiczki wieprzowe (450 g)',
// 		price: 56,
// 		description: 'Gnocchi / gulasz warzywny a la Ratatouille',
// 		category: 'Dania mięsne',
// 		image: '/img/menu/poledwiczki-wieprzowe.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Burger wołowy (550 g)',
// 		price: 59,
// 		description: 'Cheddar / boczek grillowany / sałata / pomidor / ogórek konserwowy / sos aioli / frytki / ketchup',
// 		category: 'Dania mięsne',
// 		image: '/img/menu/burger-wolowy.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Burger z chrupiącym kurczakiem (500 g)',
// 		price: 56,
// 		description: 'Cheddar / pomidor / sałata / sos aioli / prażona cebulka / frytki / ketchup',
// 		category: 'Dania mięsne',
// 		image: '/img/menu/burger-z-chrupiacym-kurczakiem.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Frytki z ketchupem (250 g)',
// 		price: 17,
// 		description: '',
// 		category: 'Dodatki',
// 		image: '/img/menu/frytki-z-ketchupem.jpg',
// 		isOrderable: true,
// 		isRecommended: true,
// 	},
// 	{
// 		name: 'Krążki cebulowe (200 g)',
// 		price: 17,
// 		description: '',
// 		category: 'Dodatki',
// 		image: '/img/menu/krazki-cebulowe.jpg',
// 		isOrderable: true,
// 		isRecommended: true,
// 	},
// 	{
// 		name: 'Surówka coleslaw (150 g)',
// 		price: 9,
// 		description: '',
// 		category: 'Dodatki',
// 		image: '/img/menu/surowka-coleslaw.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Sałatka warzywna (200 g)',
// 		price: 15,
// 		description: '',
// 		category: 'Dodatki',
// 		image: '/img/menu/salatka-warzywna.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Łódeczki ziemniaczane z aioli (250 g)',
// 		price: 17,
// 		description: '',
// 		category: 'Dodatki',
// 		image: '/img/menu/lodeczki-ziemniaczane-z-aioli.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Sos (50 g)',
// 		price: 5,
// 		description: 'bbq / sweet chilli / cream / aioli / ketchup / mayo',
// 		category: 'Dodatki',
// 		image: '/img/menu/sos.jpg',
// 		isOrderable: true,
// 		isRecommended: true,
// 	},
// 	// KIDS MENU
// 	{
// 		name: 'Zupa pomidorowa (250 ml)',
// 		price: 18,
// 		description: 'Z makaronem',
// 		category: 'Dla dzieci',
// 		image: '/img/menu/zupa-pomidorowa.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Naleśniki (200 g)',
// 		price: 26,
// 		description: 'Waniliowy twarożek / owoce / sos wiśniowy',
// 		category: 'Dla dzieci',
// 		image: '/img/menu/nalesniki.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Rigatoni pomodoro (150 g)',
// 		price: 26,
// 		description: 'Makaron w sosie pomidorowym z parmezanem',
// 		category: 'Dla dzieci',
// 		image: '/img/menu/rigatoni-pomodoro.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Pulpeciki w jasnym sosie (250 g)',
// 		price: 28,
// 		description: 'Sos śmietanowo - koperkowy / puree ziemniaczano - bazyliowe',
// 		category: 'Dla dzieci',
// 		image: '/img/menu/pulpeciki-w-jasnym-sosie.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Złociste fileciki z kurczaka (250 g)',
// 		price: 32,
// 		description: 'frytki / ketchup',
// 		category: 'Dla dzieci',
// 		image: '/img/menu/zlociste-fileciki-z-kurczaka.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Złociste fileciki z dorsza (250 g)',
// 		price: 35,
// 		description: 'frytki / ketchup',
// 		category: 'Dla dzieci',
// 		image: '/img/menu/zlociste-fileciki-z-dorsza.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	// DESSERTS
// 	{
// 		name: 'Deser dnia (150 g)',
// 		price: 22,
// 		description: 'Szarlotka / Brownie / Sernik',
// 		category: 'Desery',
// 		image: '/img/menu/deser-dnia.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Gałka lodów do deseru (30 g)',
// 		price: 5,
// 		description: '',
// 		category: 'Desery',
// 		image: '/img/menu/galka-lodow.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Bita śmietana do deseru (20 g)',
// 		price: 5,
// 		description: '',
// 		category: 'Desery',
// 		image: '/img/menu/bita-smietana.jpg',
// 		isOrderable: true,
// 		isRecommended: false,
// 	},
// 	//DRINKS
// 	//CLASIC DRINKS
// 	{
// 		name: 'Aperol Jack (1l)',
// 		price: 39,
// 		description: 'Drink w połączeniu z delikatnym Piwem Capitan Jack',
// 		category: 'Klasyczne koktaile',
// 		image: '/img/menu/aperol-jack.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Świeże Prosseco z Nalewaka (120 ml)',
// 		price: 15,
// 		description: 'Pyszne włoskie prosecco prosto ze zmrożonej beczki',
// 		category: 'Klasyczne koktaile',
// 		image: '/img/menu/prosseco-z-nalewaka.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Sangria z Owocami (300 ml)',
// 		price: 18,
// 		description: 'Tradycyjny hiszpański klasyk, na bazie wina i owoców z dodatkiem kostek lodu',
// 		category: 'Klasyczne koktaile',
// 		image: '/img/menu/sangria-z-owocami.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Lemoniada Klasyczna (300 ml)',
// 		price: 16,
// 		description: 'Cytryna / pomarańcza / cukier trzcinowy / lód',
// 		category: 'Klasyczne koktaile',
// 		image: '/img/menu/lemoniada-klasyczna.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Lemoniada Miodowa (300 ml)',
// 		price: 16,
// 		description: 'Cytryna / pomarańcza / miód / lód',
// 		category: 'Klasyczne koktaile',
// 		image: '/img/menu/lemoniada-miodowa.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	// HOT DRINKS
// 	{
// 		name: 'Czerwone wino grzane z cynamonem i goździkami (200 ml)',
// 		price: 20,
// 		description: 'czerwone wino / cynamon / goździka',
// 		category: 'Na ciepło',
// 		image: '/img/menu/wino-grzane.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Cherry Lady (300 ml)',
// 		price: 26,
// 		description: 'Herbata czarna / pomarańcza / cytryna / miód / wiśnie / 40 ml wiśniówki',
// 		category: 'Na ciepło',
// 		image: '/img/menu/cherry-lady.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Herbata rozgrzewająca (300 ml)',
// 		price: 20,
// 		description: 'pomarańcza / cytryna / imbir / cynamon / goździki / miód',
// 		category: 'Na ciepło',
// 		image: '/img/menu/herbata-rozgrzewajaca.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Aperol w ciepłej odsłonie na bazie białego wina i soku z aromatycznej pomarańczy (200 ml)',
// 		price: 20,
// 		description: 'aperol / białe wino / pomarańcza',
// 		category: 'Na ciepło',
// 		image: '/img/menu/aperol-na-cieplo.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	//TEA
// 	{
// 		name: 'Herbata Eilles (500 ml)',
// 		price: 16,
// 		description: 'czarna / earl grey / zielona / zielona z egzotycznymi owocami / zielona jaśminowa / owocowa truskawka z maliną / mięta pieprzowa / owocowa jabłkowa / owocowa pomarańcza z witaminą c',
// 		category: 'Herbata',
// 		image: '/img/menu/herbata-eilles.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	//COFFEE
// 	{
// 		name: 'Espresso (40 ml)',
// 		price: 13,
// 		description: '',
// 		category: 'Kawa',
// 		image: '/img/menu/espresso.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Espresso macchiato (50 ml)',
// 		price: 14,
// 		description: '',
// 		category: 'Kawa',
// 		image: '/img/menu/espresso-macchiato.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Espresso doppio (80 ml)',
// 		price: 20,
// 		description: '',
// 		category: 'Kawa',
// 		image: '/img/menu/espresso-doppio.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Americano (200 ml / 300 ml)',
// 		price: 14,
// 		description: '',
// 		category: 'Kawa',
// 		image: '/img/menu/americano.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Kawa biała (200 ml / 300 ml)',
// 		price: 15,
// 		description: '',
// 		category: 'Kawa',
// 		image: '/img/menu/kawa-biala.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Cappuccino (300 ml)',
// 		price: 16,
// 		description: '',
// 		category: 'Kawa',
// 		image: '/img/menu/cappuccino.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Latte (300 ml)',
// 		price: 16,
// 		description: '',
// 		category: 'Kawa',
// 		image: '/img/menu/latte.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Flat white (200 ml)',
// 		price: 20,
// 		description: '',
// 		category: 'Kawa',
// 		image: '/img/menu/flat-white.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Mocca z czekoladą / Chocolate Mocca (300 ml)',
// 		price: 20,
// 		description: '',
// 		category: 'Kawa',
// 		image: '/img/menu/mocca.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Kawa mrożona z lodami śmietankowymi (300 ml)',
// 		price: 22,
// 		description: '',
// 		category: 'Kawa',
// 		image: '/img/menu/kawa-mrozona.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Gorący napój czekoladowy z bitą śmietaną lub piankami Marschmallow (300 ml)',
// 		price: 22,
// 		description: '',
// 		category: 'Kawa',
// 		image: '/img/menu/hot-chocolate.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{

// 		name: 'Baileys Coffee (250 ml)',
// 		price: 27,
// 		description: 'americano z dodatkiem likieru śmietankowego i bitej śmietany',
// 		category: 'Kawa',
// 		image: '/img/menu/baileys-coffee.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Wedel Coffee (250 ml)',
// 		price: 27,
// 		description: 'americano z dodatkiem likieru wiśniowo - czekoladowego i bitej śmietany',
// 		category: 'Kawa',
// 		image: '/img/menu/wedel-coffee.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Amaretto Coffee (250 ml)',
// 		price: 27,
// 		description: 'americano z dodatkiem likieru migdałowego i bitej śmietany',
// 		category: 'Kawa',
// 		image: '/img/menu/amaretto-coffee.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	//COLD DRINKS
// 	{
// 		name: 'Krystaliczne źródło: gazowana / niegazowana',
// 		price: 8,
// 		description: '',
// 		category: 'Napoje zimne',
// 		image: '/img/menu/krystaliczne-zrodlo.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Pepsi / Pepsi Max / Mirinda / 7UP / Schweppes',
// 		price: 8,
// 		description: '',
// 		category: 'Napoje zimne',
// 		image: '/img/menu/pepsi.jpg',
// 		isOrderable: false,
// 		isRecommended: true,
// 	},
// 	{
// 		name: 'Lipton Ice Tea brzoskwiniowa / zielona herbata',
// 		price: 8,
// 		description: '',
// 		category: 'Napoje zimne',
// 		image: '/img/menu/lipton-ice-tea.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Sok Toma jabłkowy / pomarańczowy',
// 		price: 8,
// 		description: '',
// 		category: 'Napoje zimne',
// 		image: '/img/menu/sok-toma.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Nektar porzeczkowy',
// 		price: 8,
// 		description: '',
// 		category: 'Napoje zimne',
// 		image: '/img/menu/nektar-porzeczkowy.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Sok świeżo wyciskany – zapytaj o dostępność kelnera',
// 		price: 8,
// 		description: '',
// 		category: 'Napoje zimne',
// 		image: '/img/menu/sok-swiezo-wyciskany.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	// BOTTLED BEAR
// 	{
// 		name: 'Lech (0,5 l)',
// 		price: 16,
// 		description: '',
// 		category: 'Piwo butelkowe',
// 		image: '/img/menu/lech.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Lech Easy (0,4 l)',
// 		price: 16,
// 		description: '',
// 		category: 'Piwo butelkowe',
// 		image: '/img/menu/lech-easy.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Kozel jasny / Kozel ciemny (0,5 l)',
// 		price: 16,
// 		description: '',
// 		category: 'Piwo butelkowe',
// 		image: '/img/menu/kozel.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Hardmade Peach / Hardmade Yuzu (0,4 l)',
// 		price: 16,
// 		description: '',
// 		category: 'Piwo butelkowe',
// 		image: '/img/menu/hardmade.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Książęce Złote pszeniczne (0,5 l)',
// 		price: 16,
// 		description: '',
// 		category: 'Piwo butelkowe',
// 		image: '/img/menu/ksiazece-zlote.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Książęce Ciemne Łagodne (0,5 l)',
// 		price: 16,
// 		description: '',
// 		category: 'Piwo butelkowe',
// 		image: '/img/menu/ksiazece-ciemne.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Książęce Czerwony Lager (0,5 l)',
// 		price: 16,
// 		description: '',
// 		category: 'Piwo butelkowe',
// 		image: '/img/menu/ksiazece-czerwony.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Książęce IPA (0,5 l)',
// 		price: 16,
// 		description: '',
// 		category: 'Piwo butelkowe',
// 		image: '/img/menu/ksiazece-ipa.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Książęce Porter (0,5 l)',
// 		price: 16,
// 		description: '',
// 		category: 'Piwo butelkowe',
// 		image: '/img/menu/ksiazece-porter.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Grolsch (0,45 l)',
// 		price: 17,
// 		description: '',
// 		category: 'Piwo butelkowe',
// 		image: '/img/menu/grolsch.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Pilsner Urquell (0,5 l)',
// 		price: 17,
// 		description: '',
// 		category: 'Piwo butelkowe',
// 		image: '/img/menu/pilsner-urquell.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Sopockie piwo (0,5 l)',
// 		price: 22,
// 		description: '',
// 		category: 'Piwo butelkowe',
// 		image: '/img/menu/sopockie-piwo.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	// NON ALCOHOLIC BEAR 
// 	{
// 		name: 'Kozel 0,5 l',
// 		price: 16,
// 		description: '',
// 		category: 'Piwo bezalkoholowe',
// 		image: '/img/menu/kozel-non-alcoholic.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Lech Free Lager 0,5 l',
// 		price: 16,
// 		description: '',
// 		category: 'Piwo bezalkoholowe',
// 		image: '/img/menu/lech-free.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Lech Free Pomelo Grejpfrut 0,5 l',
// 		price: 16,
// 		description: '',
// 		category: 'Piwo bezalkoholowe',
// 		image: '/img/menu/lech-free-pomelo.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Lech Active Liczi i cytryna 0,5 l',
// 		price: 16,
// 		description: '',
// 		category: 'Piwo bezalkoholowe',
// 		image: '/img/menu/lech-active.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	// WHITE WINE
// 	{
// 		name: 'EL CAMPO CHARDONNAY / W / CHILE (DRY) (150 ml)',
// 		price: 23,
// 		description: 'Świeże, łagodne, owocowe wydanie kosmopolitycznej odmiany chardonnay. Cytrusy i dojrzałe jabłka oraz gruszki, to aromatyczny wyznacznik tego wina. W ustach świeże, intensywne o dobrze zrównoważonej kwasowości.',
// 		category: 'Wina Białe',
// 		image: '/img/menu/el-campo-chardonnay.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'EL CAMPO SAUVIGNON BLANC / W / CHILE (DRY) (150 ml)',
// 		price: 23,
// 		description: 'Jasnożółta barwa z zielonkawym połyskiem. W nosie sprężyste, cytrusowe aromaty z akcentem różowego grapefruita i agrestu. Delikatna kwasowość o odświeżającym charakterze.',
// 		category: 'Wina Białe',
// 		image: '/img/menu/el-campo-sauvignon-blanc.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'ABTEI HIMMEROD RIESLING FEINHERB / PW / NIEMCY (SEMI-DRY) (150 ml)',
// 		price: 25,
// 		description: 'Klasyczny niemiecki riesling z Doliny Mozeli w wersji półwytrawnej. Duża ilość cukru resztkowego dobrze “ukryta” została przez naturalną kwasowość, która utrzymuje wino w odpowiednim balansie i dostarcza orzeźwienia.',
// 		category: 'Wina Białe',
// 		image: '/img/menu/abtei-himmerod-riesling.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'ABTESAVEE SEA SAUVIGNON BLANC / W / NOWA ZELANDIA (DRY) (150 ml)',
// 		price: 27,
// 		description: 'Wino na wskroś soczyste i kruche w swej strukturze. Owoce tropikalne przeplatają się z aromatami grejpfruta, melona i dojrzałego agrestu. Na podniebieniu rześkie, pełne wigoru. Długie ze szczyptą marakui w finiszu.',
// 		category: 'Wina Białe',
// 		image: '/img/menu/abtesavee-sea-sauvignon-blanc.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	// RED WINE
// 	{
// 		name: 'LAYA /W / HISZPANIA (DRY)',
// 		price: 25,
// 		description: 'Pełne, intensywne czerwone wino z mocno zaakcentowanym dojrzałym ciemnym owocem, który przeplatany jest nutami czarnego pieprzu oraz przypraw korzennych. Usta pełne, dojrzałe z ciepłą, aksamitną taniną. Wino dojrzewało 4 miesiące w beczkach z francuskiego dębu. Długi owocowy finisz nie pozwala na szybkie pożegnanie z tym interesującym winem.',
// 		category: 'Wina Czerwone',
// 		image: '/img/menu/laya.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'PRIMITIVO DI MANDURIA ARCHIDAMO /W/WŁOCHY (DRY)',
// 		price: 27,
// 		description: 'To wytrawne wino o czerwonej barwie z fioletowymi refleksami produkowane w 100% ze szczepu primitivo. Część wina dojrzewa przez 8 miesięcy w dębowych beczkach. W zapachu dominują dojrzałe owoce wiśni z aromatem wanilii oraz lukrecji. Usta dobrze zbalansowane, owocowe z nutami wiśni, czekolady i lukrecji o odświeżającym charakterze.',
// 		category: 'Wina Czerwone',
// 		image: '/img/menu/primitivo-di-manduria.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	// COCTAILS
// 	{
// 		name: 'Aperol Spritz (250 ml)',
// 		price: 32,
// 		description: 'Klasyczny koktajl na bazie Aperol, Prosecco i wody gazowanej, serwowany z plastrami pomarańczy.',
// 		category: 'Drinki',
// 		image: '/img/menu/aperol-spritz.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Gin & Tonic (250 ml)',
// 		price: 32,
// 		description: '70 ml Prosseco / 70 ml świeżego soku z pomarańczy, połączone z klasycznym ginem i tonikiem.',
// 		category: 'Drinki',
// 		image: '/img/menu/gin-tonic.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Letnie Orzeźwienie (250 ml)',
// 		price: 28,
// 		description: '80 ml Martini Fiero / 100 ml Schweppes Tonic, udekorowane plastrami pomarańczy i rozmarynem.',
// 		category: 'Drinki',
// 		image: '/img/menu/letnie-orzezwienie.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Martini Tonic (250 ml)',
// 		price: 28,
// 		description: 'Koktajl na bazie Martini i toniku, serwowany z plastrami cytryny i lodem.',
// 		category: 'Drinki',
// 		image: '/img/menu/martini-tonic.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Negroni (200 ml)',
// 		price: 34,
// 		description: '40 ml Gordon’s gin / 40 ml Campari / 40 ml Martini Rossato / pomarańcza, klasyczny włoski koktajl.',
// 		category: 'Drinki',
// 		image: '/img/menu/negroni.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Mimosa (140 ml)',
// 		price: 32,
// 		description: '70 ml Prosseco / 70 ml świeżego soku z pomarańczy. Polecamy drink MIMOSA do śniadania w cenie 27 zł. SPECIAL OFFER : Order breakfast and a MIMOSA coctail for 27 zł.',
// 		category: 'Drinki',
// 		image: '/img/menu/mimosa.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	// WHISKY
// 	{
// 		name: 'Ballantines (40 ml)',
// 		price: 16,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/ballantines.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Jack Daniel’s (40 ml)',
// 		price: 18,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/jack-daniels.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Jameson (40 ml)',
// 		price: 16,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/jameson.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Bulleit Bourbon Frontier Whiskey (40 ml)',
// 		price: 22,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/bulleit-bourbon.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Chivas Regal 12 letnia (40 ml)',
// 		price: 18,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/chivas-regal-12.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Hankey Bannister (40 ml)',
// 		price: 17,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/hankey-bannister.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Hankey Bannister Heritage Blend (40 ml)',
// 		price: 19,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/hankey-bannister-heritage.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Monkey Shoulder Blended Malt (40 ml)',
// 		price: 22,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/monkey-shoulder.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Johnnie Walker Black 12 letnia (40 ml)',
// 		price: 19,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/johnnie-walker-black.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Kavalan Classic Single Malt (40 ml)',
// 		price: 37,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/kavalan-classic.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'anCnoc 12 letnia (40 ml)',
// 		price: 22,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/ancnoc-12.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Ardbeg 10 letnia (40 ml)',
// 		price: 30,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/ardbeg-10.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Old Pulteney 12 letnia (40 ml)',
// 		price: 23,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/old-pulteney-12.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Balblair 2003 Vintage (40 ml)',
// 		price: 36,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/balblair-2003.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Aberfeldy 12 letnia (40 ml)',
// 		price: 32,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/aberfeldy-12.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'The Arran Malt Amarone (40 ml)',
// 		price: 32,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/arran-malt-amarone.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Glenmorangie 10 letnia (40 ml)',
// 		price: 32,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/glenmorangie-10.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Togouchi Old Blended Whisky 18 letnia (40 ml)',
// 		price: 57,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/togouchi-18.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Bruichladdich The Classic Laddie Scottish Barley (40 ml)',
// 		price: 32,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/bruichladdich-classic-laddie.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Lagavulin 16 letnia (40 ml)',
// 		price: 44,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/lagavulin-16.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Singleton (40 ml)',
// 		price: 23,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/singleton.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Talisker (40 ml)',
// 		price: 27,
// 		description: '',
// 		category: 'Whisky',
// 		image: '/img/menu/talisker.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	// RUM
// 	{
// 		name: 'Captain Morgan (40 ml)',
// 		price: 15,
// 		description: '',
// 		category: 'Rum',
// 		image: '/img/menu/captain-morgan.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Captain Morgan Dark (40 ml)',
// 		price: 18,
// 		description: '',
// 		category: 'Rum',
// 		image: '/img/menu/captain-morgan-dark.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Captain Morgan Spice (40 ml)',
// 		price: 16,
// 		description: '',
// 		category: 'Rum',
// 		image: '/img/menu/captain-morgan-spice.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Captain Morgan Apple (40 ml)',
// 		price: 16,
// 		description: '',
// 		category: 'Rum',
// 		image: '/img/menu/captain-morgan-apple.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	// TEQUILA
// 	{
// 		name: 'Jose Cuervo Gold (40 ml)',
// 		price: 17,
// 		description: '',
// 		category: 'Tequila',
// 		image: '/img/menu/jose-cuervo-gold.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Jose Cuervo Silver (40 ml)',
// 		price: 15,
// 		description: '',
// 		category: 'Tequila',
// 		image: '/img/menu/jose-cuervo-silver.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	// COGNAC / BRANDY
// 	{
// 		name: 'Metaxa 5 (40 ml)',
// 		price: 16,
// 		description: '',
// 		category: 'Cognac / Brandy',
// 		image: '/img/menu/metaxa-5.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Metaxa 7 (40 ml)',
// 		price: 19,
// 		description: '',
// 		category: 'Cognac / Brandy',
// 		image: '/img/menu/metaxa-7.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Hennessy (40 ml)',
// 		price: 24,
// 		description: '',
// 		category: 'Cognac / Brandy',
// 		image: '/img/menu/hennessy.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	// GIN
// 	{
// 		name: 'Gordon’s (40 ml)',
// 		price: 17,
// 		description: '',
// 		category: 'Gin',
// 		image: '/img/menu/gordons.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Gordon’s Pink (40 ml)',
// 		price: 18,
// 		description: '',
// 		category: 'Gin',
// 		image: '/img/menu/gordons-pink.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Gordon’s Sicilian (40 ml)',
// 		price: 18,
// 		description: '',
// 		category: 'Gin',
// 		image: '/img/menu/gordons-sicilian.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Tanqueray London Dry (40 ml)',
// 		price: 20,
// 		description: '',
// 		category: 'Gin',
// 		image: '/img/menu/tanqueray-london-dry.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Tanqueray Sevilla (40 ml)',
// 		price: 22,
// 		description: '',
// 		category: 'Gin',
// 		image: '/img/menu/tanqueray-sevilla.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Bombay Sapphire (40 ml)',
// 		price: 19,
// 		description: '',
// 		category: 'Gin',
// 		image: '/img/menu/bombay-sapphire.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Magellan (40 ml)',
// 		price: 19,
// 		description: '',
// 		category: 'Gin',
// 		image: '/img/menu/magellan.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Bulldog London Dry (40 ml)',
// 		price: 22,
// 		description: '',
// 		category: 'Gin',
// 		image: '/img/menu/bulldog-london-dry.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Cubical Kiss Premium Dry Gin (40 ml)',
// 		price: 25,
// 		description: '',
// 		category: 'Gin',
// 		image: '/img/menu/cubical-kiss.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Vine Gin de France Floraison (40 ml)',
// 		price: 22,
// 		description: '',
// 		category: 'Gin',
// 		image: '/img/menu/vine-gin-de-france.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Hendrick’s Scotland Gin (40 ml)',
// 		price: 25,
// 		description: '',
// 		category: 'Gin',
// 		image: '/img/menu/hendricks.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Monkey 47 Schwarzwald Dry Gin (40 ml)',
// 		price: 27,
// 		description: '',
// 		category: 'Gin',
// 		image: '/img/menu/monkey-47-dry.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Monkey 47 Schwarzwald Sloe Gin (40 ml)',
// 		price: 27,
// 		description: '',
// 		category: 'Gin',
// 		image: '/img/menu/monkey-47-sloe.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Copper Head Gin (40 ml)',
// 		price: 27,
// 		description: '',
// 		category: 'Gin',
// 		image: '/img/menu/copper-head.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	// VODKA
// 	{
// 		name: 'Absolut (40 ml)',
// 		price: 16,
// 		description: '',
// 		category: 'Wódka',
// 		image: '/img/menu/absolut.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Ketel one cytrynowy (40 ml)',
// 		price: 19,
// 		description: '',
// 		category: 'Wódka',
// 		image: '/img/menu/ketel-one-cytrynowy.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Ketel one (40 ml)',
// 		price: 17,
// 		description: '',
// 		category: 'Wódka',
// 		image: '/img/menu/ketel-one.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Cana Rio Cachaca (40 ml)',
// 		price: 17,
// 		description: '',
// 		category: 'Wódka',
// 		image: '/img/menu/cana-rio-cachaca.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Chopin (40 ml)',
// 		price: 18,
// 		description: '',
// 		category: 'Wódka',
// 		image: '/img/menu/chopin.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Wyborowa (40 ml)',
// 		price: 14,
// 		description: '',
// 		category: 'Wódka',
// 		image: '/img/menu/wyborowa.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Soplica smakowa (40 ml)',
// 		price: 13,
// 		description: '',
// 		category: 'Wódka',
// 		image: '/img/menu/soplica.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// 	{
// 		name: 'Orkisz (40 ml)',
// 		price: 16,
// 		description: '',
// 		category: 'Wódka',
// 		image: '/img/menu/orkisz.jpg',
// 		isOrderable: false,
// 		isRecommended: false,
// 	},
// ]
