import { CarouselImage, MenuItemCategory, Opinion } from '@/app/types/types'

export const CAROUSEL_MAIN_IMAGES: CarouselImage[] = [
	{ src: '/img/carousel-1.jpg' },
	{ src: '/img/carousel-2.jpg' },
]

export const OPINIONS: Opinion[] = [
	{
		author: 'Edward T',
		date: '01.07.2024',
		message: 'Restauracja Spoko w Sopocie to prawdziwa perełka nadmorskiej gastronomii. Położona w urokliwym miejscu, tuż przy plaży, oferuje nie tylko przepiękne widoki na morze, ale również doskonałą kuchnię. Menu jest różnorodne i zadowoli zarówno miłośników tradycyjnych polskich smaków, jak i tych poszukujących bardziej egzotycznych dań. Świeże składniki, profesjonalna obsługa i przyjazna atmosfera sprawiają, że każda wizyta w Spoko to wyjątkowe doświadczenie. To idealne miejsce na romantyczną kolację, spotkanie z przyjaciółmi czy rodzinny obiad. Gorąco polecam!',
		rate: 5,
	},
	{
		author: 'Julia B',
		date: '3 miesiący temu',
		message: 'Dawno nie spotkaliśmy tak przemiłej i kontaktowej obsługi-to pierwszy aspekt, dla którego chce się wracać w takie miejsca! Po drugie-lokalizacja, myślę że siedząc latem na patio z widokiem na morze można się zakochać! Przechodząc do sedna-jedzenie. Uważam że sposób podania, kompozycje i jakość składników, którą jest wyczuwalna w każdym kęsie sprosta nawet najbardziej wymagającym podniebieniom :) Z pewnością wrócimy w to miejsce!',
		rate: 5,
	},
	{
		author: 'Pokochaj K',
		date: '2 miesiący temu',
		message: 'Spoko miejsce z klimatem i smacznym jedzeniem. Nero Di Seria, Bowle z Kurczkiem, Spaghetti dla dzieci wyśmienite, zupa rybna klasyczna mogłaby być bardziej treściwa. Sangria i lemoniada mega orzeźwiające. Jestem na tak i wpadnę tu jeszcze będąc na kempingu.',
		rate: 4,
	},
	{
		author: 'Kinga B',
		date: '2 miesiący temu',
		message: 'Cudowne miejsce z fantastyczną obsługa i atmosferą. Jedzenie przepyszne - polecam burgery, bardzo smaczna bułka i świeże składniki. Dodatkowo piękny widok na morze. Pani, która nas obsługiwała była uśmiechnięta, naturalna i niesamowicie kontaktowa. Mało jest już takich osób. Serdecznie dziękujemy za cudowne chwile. Ogromny plus na możliwość przyjścia z pupilami! ❤️ Pozdrawiamy serdecznie (buldożki francuskie Frania&Mia)♥️',
		rate: 5,
	},
	{
		author: 'Anna O',
		date: '5 miesięcy temu',
		message: 'Super miejsce, a obiad mega pyszny. Najlepsza lemoniada jaka piłam. Dorsz z purée ziemniaczano bazyliowym i boczniakami po kaszubsku, palce lizać',
		rate: 5,
	},
]
export const menuItemCategories: MenuItemCategory[] = [
	'Dania główne',
	'Pizza',
	'Burgery',
	'Makarony/Ravioli',
	'Dla dzieci',
	'Dodatki',
	'Desery',
	'Napoje',
	'Śniadania',
	'Przystawki',
	'Zupy',
	'Bowle',
	'Vege',
	'Dania rybne',
	'Owoce morza',
	'Dania mięsne',
	'Klasyczne koktaile',
	'Na ciepło',
	'Herbata',
	'Kawa',
	'Napoje zimne',
	'Piwo butelkowe',
	'Piwo bezalkoholowe',
	'Piwo beczkowe',
	'Piwo smakowe',
	'Wina Białe',
	'Wina Czerwone',
	'Wina Musujące',
	'Drinki',
	'Whisky',
	'Rum',
	'Gin',
	'Tequila',
	'Cognac / Brandy',
	'Wódka',
	'Napoje alkoholowe',
	'Napoje bezalkoholowe',
	'Napoje łekkoprocentowe',
	'Inne'
]
